// @/lib/data.ts
'strict';

import { Project } from "./types";

// === 1. Projects (Minimal) ===
export const projects = [
  {
    ProjectID: 1,
    ProjectName: 'Downtown Office Renovation',
    QuotedCost: 125000.5,
    Status: 'Active' as const,
    QuoteDate: '2024-03-15',
  },
  {
    ProjectID: 2,
    ProjectName: 'Residential Kitchen Remodel',
    QuotedCost: 45000.0,
    Status: 'Completed' as const,
    QuoteDate: '2024-01-20',
  },
  {
    ProjectID: 3,
    ProjectName: 'Commercial Warehouse Expansion',
    QuotedCost: 250000.75,
    Status: 'In Progress' as const,
    QuoteDate: '2024-06-10',
  },
] as const;

// === 2. Jobs (with Gantt fields) ===
export const jobs = [
  {
    JobID: 101,
    ProjectID: 1,
    JobName: 'Electrical Wiring',
    JobBudget: 25000.0,
    Status: 'In Progress' as const,
    StartDate: '2024-04-01',
    Duration: 15,
    Progress: 0.4,
    PredecessorJobID: null,
  },
  {
    JobID: 102,
    ProjectID: 1,
    JobName: 'Plumbing Installation',
    JobBudget: 18000.0,
    Status: 'Active' as const,
    StartDate: '2024-04-10',
    Duration: 20,
    Progress: 0.3,
    PredecessorJobID: 101,
  },
  {
    JobID: 103,
    ProjectID: 2,
    JobName: 'Cabinet Installation',
    JobBudget: 12000.0,
    Status: 'Completed' as const,
    StartDate: '2024-02-15',
    Duration: 14,
    Progress: 1.0,
    PredecessorJobID: null,
  },
  {
    JobID: 104,
    ProjectID: 3,
    JobName: 'Foundation Work',
    JobBudget: 60000.0,
    Status: 'In Progress' as const,
    StartDate: '2024-07-01',
    Duration: 20,
    Progress: 0.45,
    PredecessorJobID: null,
  },
  {
    JobID: 105,
    ProjectID: 3,
    JobName: 'Structural Steel',
    JobBudget: 45000.0,
    Status: 'Active' as const,
    StartDate: '2024-07-15',
    Duration: 30,
    Progress: 0.2,
    PredecessorJobID: 104,
  },
] as const;

// === 3. Tasks (Sub-tasks of Jobs) ===
export const tasks = [
  {
    TaskID: 1001,
    JobID: 101,
    TaskName: 'Install Main Panel',
    TaskBudget: 5000.0,
    Status: 'In Progress' as const,
    DueDate: '2024-04-15',
    Progress: 0.5,
  },
  {
    TaskID: 1002,
    JobID: 101,
    TaskName: 'Wire Outlets',
    TaskBudget: 3000.0,
    Status: 'Not Started' as const,
    DueDate: '2024-04-20',
    Progress: 0.0,
  },
  {
    TaskID: 1003,
    JobID: 102,
    TaskName: 'Lay Pipes',
    TaskBudget: 4000.0,
    Status: 'Completed' as const,
    DueDate: '2024-04-25',
    Progress: 1.0,
  },
  {
    TaskID: 1004,
    JobID: 102,
    TaskName: 'Install Fixtures',
    TaskBudget: 2500.0,
    Status: 'In Progress' as const,
    DueDate: '2024-05-01',
    Progress: 0.7,
  },
  {
    TaskID: 1005,
    JobID: 103,
    TaskName: 'Measure and Cut',
    TaskBudget: 2000.0,
    Status: 'Completed' as const,
    DueDate: '2024-02-20',
    Progress: 1.0,
  },
  {
    TaskID: 1006,
    JobID: 103,
    TaskName: 'Assemble and Install',
    TaskBudget: 3500.0,
    Status: 'Completed' as const,
    DueDate: '2024-02-28',
    Progress: 1.0,
  },
  {
    TaskID: 1007,
    JobID: 104,
    TaskName: 'Excavate Site',
    TaskBudget: 10000.0,
    Status: 'In Progress' as const,
    DueDate: '2024-07-10',
    Progress: 0.4,
  },
  {
    TaskID: 1008,
    JobID: 104,
    TaskName: 'Pour Concrete',
    TaskBudget: 15000.0,
    Status: 'Not Started' as const,
    DueDate: '2024-07-20',
    Progress: 0.0,
  },
  {
    TaskID: 1009,
    JobID: 105,
    TaskName: 'Fabricate Beams',
    TaskBudget: 8000.0,
    Status: 'Active' as const,
    DueDate: '2024-07-25',
    Progress: 0.6,
  },
  {
    TaskID: 1010,
    JobID: 105,
    TaskName: 'Erect Framework',
    TaskBudget: 12000.0,
    Status: 'Not Started' as const,
    DueDate: '2024-08-10',
    Progress: 0.0,
  },
  {
    TaskID: 1011,
    JobID: 101,
    TaskName: 'Test Electrical System',
    TaskBudget: 1500.0,
    Status: 'Not Started' as const,
    DueDate: '2024-04-25',
    Progress: 0.0,
  },
  {
    TaskID: 1012,
    JobID: 102,
    TaskName: 'Pressure Test Pipes',
    TaskBudget: 1000.0,
    Status: 'Completed' as const,
    DueDate: '2024-04-22',
    Progress: 1.0,
  },
] as const;

// === 4. Task Progress (History) ===
export const taskProgress = [
  {
    ProgressID: 4001,
    TaskID: 1001,
    Date: '2024-04-10',
    Percentage: 50,
    Notes: 'Panel mounted and wired halfway',
  },
  {
    ProgressID: 4002,
    TaskID: 1003,
    Date: '2024-04-20',
    Percentage: 100,
    Notes: 'All pipes laid and tested',
  },
  {
    ProgressID: 4003,
    TaskID: 1004,
    Date: '2024-04-28',
    Percentage: 70,
    Notes: 'Sinks installed, faucets pending',
  },
  {
    ProgressID: 4004,
    TaskID: 1005,
    Date: '2024-02-18',
    Percentage: 100,
    Notes: 'All measurements taken and cuts made',
  },
  {
    ProgressID: 4005,
    TaskID: 1006,
    Date: '2024-02-25',
    Percentage: 100,
    Notes: 'Cabinets fully installed',
  },
  {
    ProgressID: 4006,
    TaskID: 1007,
    Date: '2024-07-08',
    Percentage: 40,
    Notes: 'Excavation ongoing',
  },
  {
    ProgressID: 4007,
    TaskID: 1009,
    Date: '2024-07-20',
    Percentage: 60,
    Notes: 'Beams partially fabricated',
  },
  {
    ProgressID: 4008,
    TaskID: 1012,
    Date: '2024-04-22',
    Percentage: 100,
    Notes: 'All tests passed',
  },
] as const;

// === 5. Materials ===
export const materials = [
  {
    MaterialID: 5001,
    TaskID: 1001,
    Name: 'Electrical Panel',
    Quantity: 1,
    Cost: 1200.0,
  },
  { MaterialID: 5002, TaskID: 1001, Name: 'Wires', Quantity: 100, Cost: 500.0 },
  {
    MaterialID: 5003,
    TaskID: 1002,
    Name: 'Outlet Boxes',
    Quantity: 20,
    Cost: 200.0,
  },
  {
    MaterialID: 5004,
    TaskID: 1003,
    Name: 'PVC Pipes',
    Quantity: 50,
    Cost: 800.0,
  },
  { MaterialID: 5005, TaskID: 1004, Name: 'Sinks', Quantity: 5, Cost: 750.0 },
  {
    MaterialID: 5006,
    TaskID: 1005,
    Name: 'Measuring Tape',
    Quantity: 2,
    Cost: 50.0,
  },
  {
    MaterialID: 5007,
    TaskID: 1006,
    Name: 'Cabinets',
    Quantity: 10,
    Cost: 2000.0,
  },
  {
    MaterialID: 5008,
    TaskID: 1007,
    Name: 'Excavation Tools',
    Quantity: 5,
    Cost: 1500.0,
  },
  {
    MaterialID: 5009,
    TaskID: 1008,
    Name: 'Concrete Mix',
    Quantity: 200,
    Cost: 8000.0,
  },
  {
    MaterialID: 5010,
    TaskID: 1009,
    Name: 'Steel Beams',
    Quantity: 15,
    Cost: 3000.0,
  },
  {
    MaterialID: 5011,
    TaskID: 1010,
    Name: 'Bolts and Nuts',
    Quantity: 500,
    Cost: 1000.0,
  },
  {
    MaterialID: 5012,
    TaskID: 1011,
    Name: 'Testing Equipment',
    Quantity: 1,
    Cost: 800.0,
  },
] as const;

// === 6. Task Photos ===
export const taskPhotos = [
  {
    PhotoID: 6001,
    TaskID: 1001,
    Url: 'https://example.com/photos/task1001_01.jpg',
    DateTaken: '2024-04-10',
  },
  {
    PhotoID: 6002,
    TaskID: 1003,
    Url: 'https://example.com/photos/task1003_01.jpg',
    DateTaken: '2024-04-20',
  },
  {
    PhotoID: 6003,
    TaskID: 1004,
    Url: 'https://example.com/photos/task1004_01.jpg',
    DateTaken: '2024-04-28',
  },
  {
    PhotoID: 6004,
    TaskID: 1006,
    Url: 'https://example.com/photos/task1006_01.jpg',
    DateTaken: '2024-02-25',
  },
  {
    PhotoID: 6005,
    TaskID: 1007,
    Url: 'https://example.com/photos/task1007_01.jpg',
    DateTaken: '2024-07-08',
  },
  {
    PhotoID: 6006,
    TaskID: 1012,
    Url: 'https://example.com/photos/task1012_01.jpg',
    DateTaken: '2024-04-22',
  },
] as const;

// === 7. Invoices ===
export const invoices = [
  {
    InvoiceID: 3001,
    JobID: 101,
    AmountDue: 8000.0,
    PaymentStatus: 'Partially Paid' as const,
  },
  {
    InvoiceID: 3002,
    JobID: 102,
    AmountDue: 5000.0,
    PaymentStatus: 'Paid' as const,
  },
  {
    InvoiceID: 3003,
    JobID: 103,
    AmountDue: 12000.0,
    PaymentStatus: 'Paid' as const,
  },
  {
    InvoiceID: 3004,
    JobID: 104,
    AmountDue: 20000.0,
    PaymentStatus: 'Unpaid' as const,
  },
  {
    InvoiceID: 3005,
    JobID: 105,
    AmountDue: 15000.0,
    PaymentStatus: 'Partially Paid' as const,
  },
  {
    InvoiceID: 3006,
    JobID: 101,
    AmountDue: 3500.0,
    PaymentStatus: 'Unpaid' as const,
  },
  {
    InvoiceID: 3007,
    JobID: 103,
    AmountDue: 2500.0,
    PaymentStatus: 'Paid' as const,
  },
  {
    InvoiceID: 3008,
    JobID: 104,
    AmountDue: 10000.0,
    PaymentStatus: 'Partially Paid' as const,
  },
] as const;

// === 8. Payments ===
export const payments = [
  {
    PaymentID: 7001,
    InvoiceID: 3001,
    Amount: 4000.0,
    PaymentDate: '2024-04-15',
    Method: 'Bank Transfer',
  },
  {
    PaymentID: 7002,
    InvoiceID: 3001,
    Amount: 2000.0,
    PaymentDate: '2024-05-01',
    Method: 'Credit Card',
  },
  {
    PaymentID: 7003,
    InvoiceID: 3002,
    Amount: 5000.0,
    PaymentDate: '2024-04-20',
    Method: 'Bank Transfer',
  },
  {
    PaymentID: 7004,
    InvoiceID: 3003,
    Amount: 6000.0,
    PaymentDate: '2024-03-05',
    Method: 'Check',
  },
  {
    PaymentID: 7005,
    InvoiceID: 3003,
    Amount: 6000.0,
    PaymentDate: '2024-03-10',
    Method: 'Bank Transfer',
  },
  {
    PaymentID: 7006,
    InvoiceID: 3005,
    Amount: 7500.0,
    PaymentDate: '2024-07-25',
    Method: 'Bank Transfer',
  },
  {
    PaymentID: 7007,
    InvoiceID: 3007,
    Amount: 2500.0,
    PaymentDate: '2024-03-15',
    Method: 'Credit Card',
  },
  {
    PaymentID: 7008,
    InvoiceID: 3008,
    Amount: 5000.0,
    PaymentDate: '2024-07-30',
    Method: 'Check',
  },
] as const;

// === 9. Change Orders ===
export const changeOrders = [
  {
    ChangeOrderID: 201,
    ProjectID: 1,
    Description: 'Additional Lighting Fixtures',
    CostImpact: 5000.0,
  },
  {
    ChangeOrderID: 202,
    ProjectID: 3,
    Description: 'Extended Roof Area',
    CostImpact: 15000.0,
  },
  {
    ChangeOrderID: 203,
    ProjectID: 1,
    Description: 'Upgrade to LED Lighting System',
    CostImpact: 3000.0,
  },
  {
    ChangeOrderID: 204,
    ProjectID: 2,
    Description: 'Change to Quartz Countertops',
    CostImpact: 2500.0,
  },
  {
    ChangeOrderID: 205,
    ProjectID: 3,
    Description: 'Additional Structural Supports',
    CostImpact: 8000.0,
  },
  {
    ChangeOrderID: 206,
    ProjectID: 1,
    Description: 'Extra Electrical Outlets',
    CostImpact: 1200.0,
  },
] as const;

// === 10. Task Catalogue (Templates) ===
export const taskCatalogue = [
  {
    CatalogueItemID: 1,
    ItemDescription: 'Installation of standard wooden door',
    DefaultRate: 950,
    UnitOfMeasure: 'per item',
    Category: 'Carpentry',
  },
  {
    CatalogueItemID: 2,
    ItemDescription: 'Basic electrical wiring for outlets',
    DefaultRate: 150,
    UnitOfMeasure: 'per outlet',
    Category: 'Electrical',
  },
  {
    CatalogueItemID: 3,
    ItemDescription: 'PVC pipe laying and jointing',
    DefaultRate: 80,
    UnitOfMeasure: 'per meter',
    Category: 'Plumbing',
  },
  {
    CatalogueItemID: 4,
    ItemDescription: 'Concrete pouring for foundation',
    DefaultRate: 1200,
    UnitOfMeasure: 'per cubic meter',
    Category: 'Masonry',
  },
  {
    CatalogueItemID: 5,
    ItemDescription: 'Cabinet assembly and installation',
    DefaultRate: 450,
    UnitOfMeasure: 'per unit',
    Category: 'Carpentry',
  },
  {
    CatalogueItemID: 6,
    ItemDescription: 'Structural steel beam fabrication',
    DefaultRate: 2500,
    UnitOfMeasure: 'per beam',
    Category: 'Metalwork',
  },
  {
    CatalogueItemID: 7,
    ItemDescription: 'Site excavation for foundation',
    DefaultRate: 300,
    UnitOfMeasure: 'per cubic meter',
    Category: 'Earthworks',
  },
  {
    CatalogueItemID: 8,
    ItemDescription: 'Electrical panel installation and testing',
    DefaultRate: 2000,
    UnitOfMeasure: 'per panel',
    Category: 'Electrical',
  },
  {
    CatalogueItemID: 9,
    ItemDescription: 'Plumbing fixture installation (sinks)',
    DefaultRate: 350,
    UnitOfMeasure: 'per fixture',
    Category: 'Plumbing',
  },
  {
    CatalogueItemID: 10,
    ItemDescription: 'Pressure testing of pipe systems',
    DefaultRate: 500,
    UnitOfMeasure: 'per system',
    Category: 'Plumbing',
  },
  {
    CatalogueItemID: 11,
    ItemDescription: 'Painting and finishing walls',
    DefaultRate: 25,
    UnitOfMeasure: 'per square meter',
    Category: 'Finishing',
  },
  {
    CatalogueItemID: 12,
    ItemDescription: 'Roofing sheet installation',
    DefaultRate: 180,
    UnitOfMeasure: 'per square meter',
    Category: 'Roofing',
  },
  {
    CatalogueItemID: 13,
    ItemDescription: 'Tile laying for floors',
    DefaultRate: 120,
    UnitOfMeasure: 'per square meter',
    Category: 'Finishing',
  },
  {
    CatalogueItemID: 14,
    ItemDescription: 'Window frame installation',
    DefaultRate: 750,
    UnitOfMeasure: 'per window',
    Category: 'Carpentry',
  },
  {
    CatalogueItemID: 15,
    ItemDescription: 'Lighting fixture mounting',
    DefaultRate: 200,
    UnitOfMeasure: 'per fixture',
    Category: 'Electrical',
  },
] as const;
